# Web UI / REST API Service
apiVersion: v1
kind: Service
metadata:
  name: {{ include "emberburn.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "emberburn.labels" . | nindent 4 }}
    service-type: webui
    embernet.ai/app-name: {{ .Values.embernet.appName | default .Chart.Name | quote }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.flux.expose }}
    flux.embernet.ai/expose: "true"
    flux.embernet.ai/service-name: {{ .Values.flux.serviceName | default .Chart.Name | quote }}
    flux.embernet.ai/port: {{ .Values.flux.port | default .Values.service.webui.port | quote }}
    flux.embernet.ai/role-attributes: {{ .Values.flux.roleAttributes | default "gui-services" | quote }}
    {{- end }}
    {{- with .Values.service.webui.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.webui.type }}
  ports:
  - name: webui
    port: {{ .Values.service.webui.port }}
    targetPort: {{ .Values.service.webui.targetPort }}
    protocol: {{ .Values.service.webui.protocol }}
    {{- if and (eq .Values.service.webui.type "NodePort") .Values.service.webui.nodePort }}
    nodePort: {{ .Values.service.webui.nodePort }}
    {{- end }}
  selector:
    {{- include "emberburn.selectorLabels" . | nindent 4 }}
